source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'gRPC', :path => '../../../grpc'

target 'AuthSample' do
  # Depend on the generated AuthTestService library.
  pod 'AuthTestService', :path => '.'

  # Depend on Google's OAuth2 library
  pod 'Google/SignIn'
end
